line-length = 79
target-version = "py311"
extend-exclude = ["migrations/versions"]

[lint]
select = ["A", "ANN", "B", "C4", "D", "E", "F", "I", "N", "RET", "SIM", "UP", "W"]
ignore = ["D203", "D213"]

[lint.per-file-ignores]
"tests/*" = ["D100", "D101", "D102", "D103", "D104", "D401"]
