"""initial schema

Revision ID: ed949cbce4b1
Revises: 
Create Date: 2026-09-17 02:29:34.214368
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed949cbce4b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bluesky_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=False),
    sa.Column('pds_host', sa.String(length=255), nullable=False),
    sa.Column('encrypted_app_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('follows_count', sa.Integer(), nullable=False),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.Column('stats_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle')
    )
    op.create_table('discord_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('test_channel_id', sa.String(length=32), nullable=False),
    sa.Column('encrypted_bot_token', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('stats_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discord_servers')
    op.drop_table('bluesky_accounts')
    # ### end Alembic commands ###
